Add ffmpeg 5.1.2
unikraft/dynamic-apps pull request #49
Opened 2023-07-15 08:52 UTC by timmmyeo

Add ffmpeg 5.1.2 dynamic executable with dependencies

2023-07-15 10:04 UTC, StefanJum requested changes
@timmmyeo this looks good, thank you.
Please remove the `usr/share` directory, since it is not needed, and add a `README.md` file where you give instructions on how to run the elf files both natively on Linux and on Unikraft (using the `run.sh` script).

2023-07-16 13:28 UTC, StefanJum requested changes
Few more comments.
@timmmyeo it seems like there are a lot more libraries added then there are dependencies. See which of them are not needed and remove them.

2023-07-16 13:28 UTC, StefanJum commented on ffmpeg/README.md
> +```console
```suggestion
Run it with the command:

```console
```

2023-07-16 13:28 UTC, StefanJum commented on ffmpeg/README.md
> +The binary is located in the `/usr/bin`` directory.
```suggestion
The binary is located in the `./usr/bin` directory.
```

2023-07-16 13:28 UTC, StefanJum commented on ffmpeg/README.md
> +```console
```suggestion
Run the `run.sh` script from the [`run-app-elfloader` repository](https://github.com/unikraft/run-app-elfloader):

```console
```

2023-07-16 13:28 UTC, StefanJum commented on ffmpeg/README.md
> +```console
```suggestion
Run a simple encode job:

```console
```

2023-07-17 23:26 UTC, timmmyeo commented
> Few more comments. @timmmyeo it seems like there are a lot more libraries added then there are dependencies. See which of them are not needed and remove them.

I tried running the application without each one of the libraries, and it seems that ffmpeg actually needs them. All the files included seem to be needed.

2023-07-21 06:50 UTC, StefanJum requested changes
Few more minor comments @timmmyeo, also please remove the parts of the commit description that are related to integrating review comments.
All good besides that.

2023-07-21 06:50 UTC, StefanJum commented on ffmpeg/README.md
> +Make sure you have the *run-app-elfloader* repository [run-app-elfloader](https://github.com/unikraft/run-app-elfloader).
```suggestion
Make sure you have the [`run-app-elfloader` repository](https://github.com/unikraft/run-app-elfloader) cloned.
```

2023-07-21 06:50 UTC, StefanJum commented on ffmpeg/README.md
> +
```suggestion
```

2023-09-09 13:26 UTC, StefanJum approved these changes
Thank you @timmmyeo.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-09 13:26 UTC, merged