Add iputils
unikraft/dynamic-apps pull request #50
Opened 2023-07-15 09:05 UTC by andreistan26

#20

2023-07-15 10:19 UTC, StefanJum requested changes
This looks good, please add a `README.md` file where you specify how to run the apps (both under Linux and under Unikraft, using `run.sh`).

Also please update the commit message and description to something more descriptive (see the [Unikraft contributing guidelines](https://unikraft.org/docs/contributing/submitting-changes/#commits)).

2023-07-15 13:55 UTC, StefanJum requested changes
Thank you @andreistan26, the REAMDE file needs to be a bit more detailed, see [this file](https://github.com/unikraft/dynamic-apps/blob/877724017397574d435236c39defd1cefc6a7e68/lang/lua/README.md) for reference

2023-07-15 13:55 UTC, StefanJum commented on iputils/README.md
> +
```suggestion
```

2023-07-15 13:55 UTC, StefanJum commented on iputils/README.md
> +```
```suggestion
All of the applications need networking so we need to use the option `-n` we can use the following command to run any of the binaries. This example is for ping:

```console
```

2023-07-15 13:55 UTC, StefanJum commented on iputils/README.md
> +## Running on Unikraft
Add a new line before and after code snippets

2023-07-15 13:55 UTC, StefanJum commented on iputils/README.md
> +```
Add a new line before and after code snippets

2023-07-15 13:55 UTC, StefanJum commented on iputils/README.md
> +Run the binaries using (for example) the following commands
Add a new line before and after headers

2023-07-15 14:59 UTC, razvand requested changes

2023-07-15 14:59 UTC, razvand commented on iputils/README.md
> +# Running iputils
Add intro about the tools and the purpose of this directory. See the [`README.md` file in the `lang/lua/` directory](https://github.com/unikraft/dynamic-apps/blob/master/lang/lua/README.md).

2023-07-15 14:59 UTC, razvand commented on iputils/README.md
> +# Running iputils
Also add similar contents and wording.

2023-07-15 14:59 UTC, razvand commented on iputils/README.md
> +```
Add space before and after code snippets.

2023-07-15 14:59 UTC, razvand commented on iputils/README.md
> +```
Mark `console` type for snippets, after triple backticks.

2023-07-15 14:59 UTC, razvand commented on iputils/README.md
> +All of the applications need networking so we need to use the option `-n` we can use the following command to run any of the binaries. This example is for ping:
```suggestion
All of the applications need networking so we need to use the option `-n`.
We can use the following command to run any of the binaries.
This example is for `ping`:
```

2023-07-15 14:59 UTC, razvand commented on iputils/README.md
> +All of the applications need networking so we need to use the option `-n` we can use the following command to run any of the binaries. This example is for ping:
One sentence per line.

2023-07-15 15:36 UTC, razvand requested changes
@andreistan26, see my comments. Take a peek into the [`README.md` file for `lang/lua`](https://github.com/unikraft/dynamic-apps/blob/master/lang/lua/README.md).

2023-07-15 15:36 UTC, razvand commented on iputils/README.md
> +# Iputils Dynamic Build
```suggestion
# iputils as Dynamic (PIE) Executables

```

2023-07-15 15:36 UTC, razvand commented on iputils/README.md
> +# Iputils Dynamic Build
Add new line after section title.

2023-07-15 15:36 UTC, razvand commented on iputils/README.md
> +``` console
Remove empty space between backtick and `console`.

2023-07-15 15:36 UTC, razvand commented on iputils/README.md
> +binary as well as the library dependencies for running inside of Unikraft.
Add wording as in the [`README.md` file for `lang/lua`](https://github.com/unikraft/dynamic-apps/blob/master/lang/lua/README.md#lua-as-dynamic-pie-executable).

2023-07-15 15:36 UTC, razvand commented on iputils/README.md
> +## Run Iputils Natively on Linux
```suggestion
## Run iputils Natively on Linux

```

2023-07-15 15:36 UTC, razvand commented on iputils/README.md
> +All of the applications need networking so we need to use the option `-n`.
```suggestion
To run the binary ELF on Unikraft, run the `run.sh` script from the [`run-app-elfloader` repository](https://github.com/unikraft/run-app-elfloader):
All of the applications need networking so we need to use the option `-n`.
```

2023-07-15 15:36 UTC, razvand commented on iputils/README.md
> +## Run Iputils with Unikraft
```suggestion
## Run iputils with Unikraft
```

2023-07-15 15:36 UTC, razvand commented on iputils/README.md
> +``` console
Remove space between backticks and `console`.

2023-07-15 15:36 UTC, razvand commented on iputils/README.md
> +binary as well as the library dependencies for running inside of Unikraft.
Do a listing of the executables and their purpose.

2023-07-16 07:34 UTC, andreistan26 commented
Definitely looks better now, should be good to go for another review.

2023-07-16 13:04 UTC, StefanJum requested changes
Only one comment @andreistan26, all good besides that

2023-07-16 13:04 UTC, StefanJum commented on iputils/README.md
> +sudo ./run.sh -n -k app-elfloader_qemu-x86_64 -r ./dynamic-apps/iputils ./bin/ping 8.8.8.8
```suggestion
sudo ./run.sh -n -k app-elfloader_qemu-x86_64 -r ../dynamic-apps/iputils ./bin/ping 8.8.8.8
```

2023-07-17 12:08 UTC, StefanJum approved these changes
See the few minor comments, I'm all good after that.

@razvand please also take a look over this.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-17 12:08 UTC, StefanJum commented on iputils/README.md
> +All of the applications need networking so we have to use the option `-n`.
```suggestion
All the applications need networking, so we have to use the option `-n`.
```

2023-07-17 12:08 UTC, StefanJum commented on iputils/README.md
> +All files are stored in their expected location in the Linux filesytem hierarchy.
```suggestion
All files are stored in their expected location from the Linux filesytem hierarchy. 
```

2023-07-21 07:13 UTC, razvand requested changes
@andreistan26, see my minor comments. Other than that, everything works. Excellent work!

After you apply my requested changes, I will then approve this and it will be upstream.

2023-07-21 07:13 UTC, razvand commented on iputils/README.md
> +This directory stores the binary executable (ELF - Executable and Linkable Format), dynamic library dependencies and support files to run the applications provided by iputils.
```suggestion
This directory stores the binary executable (ELF - Executable and Linkable Format), dynamic library dependencies and support files to run the applications provided by iputils.
```

2023-07-21 07:13 UTC, razvand commented on iputils/README.md
> +All files are stored in their expected location from the Linux filesytem hierarchy.
```suggestion
All files are stored in their expected location from the Linux filesytem hierarchy.
```

2023-07-21 07:13 UTC, razvand commented on iputils/README.md
> +```console
Removing trailing white space.

2023-07-21 07:14 UTC, razvand requested changes

2023-07-21 07:14 UTC, razvand commented on iputils/README.md
> +- [tracepath](https://man7.org/linux/man-pages/man8/tracepath.8.html) - traces path to a network host
```suggestion
- [tracepath](https://man7.org/linux/man-pages/man8/tracepath.8.html) - trace path to a network host
```

2023-07-30 14:06 UTC, RaduNichita approved these changes
All good from my side. Thanks, @andreistan26 !

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-07-30 14:30 UTC, closed without merging