Add lua-build files
unikraft/dynamic-apps pull request #51
Opened 2023-07-15 09:35 UTC by razvang0307

Adds a lua interpreter app (built from source).

2023-07-15 10:56 UTC, StefanJum requested changes
Thank you @razvang0307.

* The script should remove the `tar` archive at the end of the execution.
* The final directory structure should be the current directory (not ./app-lua)
* Please update the `README.md` file with instructions and output on how to run the application, both on Linux and on top of Unikraft (using the `run.sh` script)
* Add a `helloworld.lua` file that we can test the application with
* Change the directory name from `lang/app-lua-source/` to `lang/lua-src/`

2023-07-15 11:54 UTC, razvang0307 commented
Updated functionality of script and README.

2023-07-15 14:10 UTC, StefanJum requested changes
Thanks.

Besides the comments, please:
* [Squash](https://www.baeldung.com/ops/git-squash-commits) and [`sign-off`](https://docs.pi-hole.net/guides/github/how-to-signoff/) the commits
* Run the script through [shellcheck](https://www.shellcheck.net/)

2023-07-15 14:10 UTC, StefanJum commented on lang/lua-src/README.md
> +```
```suggestion
```console
```

2023-07-15 14:10 UTC, StefanJum commented on lang/lua-src/README.md
> +```
```suggestion
```console
```

2023-07-15 14:10 UTC, StefanJum commented on lang/lua-src/README.md
> +### Usage
```suggestion
# Usage
```

2023-07-15 14:10 UTC, StefanJum commented on lang/lua-src/README.md
> +`file.lua` needs to be placed in the app-lua directory.
You can add a simple helloworld lua file

2023-07-15 14:10 UTC, StefanJum commented on lang/lua-src/build.sh
> +cd 'lua-5.4.6'
```suggestion
push "lua-5.4.6" &> /dev/null || exit 1
```

2023-07-15 14:10 UTC, StefanJum commented on lang/lua-src/build.sh
> +cd ../
```suggestion
popd &> /dev/null || exit 1
```

2023-07-15 14:10 UTC, StefanJum commented on lang/lua-src/build.sh
> +cd app-lua
```suggestion
pushd app-lua &> /dev/null || exit 1
```

2023-07-15 14:10 UTC, StefanJum commented on lang/lua-src/build.sh
> +cd ../
```suggestion
popd &> /dev/null || exit 1
```

2023-07-17 12:13 UTC, StefanJum requested changes
See the few more comments. Also please mark the conversations as resolved after you integrate the changes, and add a `helloworld.lua` test file.

2023-07-17 12:13 UTC, StefanJum commented on lang/lua-src/README.md
> +Run the `./script.sh` script. This will download, extract and build lua in the app-lua directory.
```suggestion
Run the `./script.sh` script.
This will download, extract and build Lua in the `app-lua` directory.
```

2023-07-17 12:13 UTC, StefanJum commented on lang/lua-src/README.md
> +With no arguments, it will open the lua console.
```suggestion
With no arguments, it will open the Lua console.
```

2023-07-17 12:13 UTC, StefanJum commented on lang/lua-src/README.md
> +`file.lua` needs to be placed in the app-lua directory.
```suggestion
`file.lua` needs to be placed in the `app-lua` directory.
```

2023-07-17 12:13 UTC, StefanJum commented on lang/lua-src/README.md
> +Otherwise, if the file is omitted, it will open the lua console.
```suggestion
Otherwise, if the file is omitted, it will open the Lua console.
```

2023-07-30 08:42 UTC, RaduNichita requested changes

2023-07-30 08:42 UTC, RaduNichita commented on lang/lua-src/README.md
> +Run the `./script.sh` script.
```suggestion
Run the `./build.sh` script.
```

2023-07-30 08:42 UTC, RaduNichita commented on lang/lua-src/README.md
> +`file.lua` needs to be placed in the `app-lua` directory.
Could you provide an example with the `1  + 1` console example for Unikraft,  to have something similar with the Linux section above

2023-07-30 08:42 UTC, RaduNichita commented on lang/lua-src/build.sh
> +echo -n "Downloading lua ... "
```suggestion
echo -n "Downloading lua-5.4.6... "
```

2023-07-30 08:42 UTC, RaduNichita commented on lang/lua-src/build.sh
> +
I think it would be useful to add a VARIABLE `VERSION=5.4.6`, to be easy to update in the future.

2023-07-30 08:53 UTC, RaduNichita approved these changes
All good now, thanks @StefanJum and @razvang0307 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-07-30 09:01 UTC, StefanJum approved these changes
Thank you @razvang0307, all good now.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-30 09:01 UTC, merged