Add ffmpeg-source
unikraft/dynamic-apps pull request #55
Opened 2023-07-15 11:11 UTC by razvang0307

Add ffmpeg-source

2023-07-15 11:29 UTC, RaduNichita requested changes
Nice work, @razvang0307. :100:  Please see my changes.

Also, change the commit message to be something more descriptive. You can check [Unikraft contributing guidelines](https://unikraft.org/docs/contributing/submitting-changes/#commits).

2023-07-15 11:29 UTC, RaduNichita commented on app-ffmpeg-source/README.md
> +### Usage
Please add more details on how to run the application. You can use [this README file](https://github.com/unikraft/dynamic-apps/blob/bf3a5a2febccb0a8f507fe0b70e7a1db48cbbe3b/lang/lua/README.md?plain=1) for reference.

2023-07-15 11:29 UTC, RaduNichita commented on app-ffmpeg-source/README.md
> +Clone this repository, run the `./script.sh` script and use `app-elfloader` using `app-ffmpeg` as the mounted filesystem.
Please rename the script to  `build.sh`

2023-07-15 11:29 UTC, RaduNichita commented on app-ffmpeg-source/script.sh
> +cd ffmpeg
```suggestion
pushd iputils &> /dev/null || exit 1
```

2023-07-15 11:29 UTC, RaduNichita commented on app-ffmpeg-source/script.sh
> +cd ../
```suggestion
popd &> /dev/null
```

2023-07-15 11:29 UTC, RaduNichita commented on app-ffmpeg-source/script.sh
> +cd app-ffmpeg
```suggestion
pushd app-ffmpeg &> /dev/null || exit 1
```

2023-07-15 11:29 UTC, RaduNichita commented on app-ffmpeg-source/script.sh
> +echo "Configuring ffmpeg ... "
```suggestion
echo "Configuring ffmpeg... "
```

2023-07-15 11:29 UTC, RaduNichita commented on app-ffmpeg-source/script.sh
> +echo -n "Cloning ffmpeg ... "
```suggestion
echo -n "Cloning ffmpeg..."
```

2023-07-15 11:29 UTC, RaduNichita commented on app-ffmpeg-source/script.sh
> +echo "Building ffmpeg ... "
```suggestion
echo "Building ffmpeg..."
```

2023-07-15 12:48 UTC, RaduNichita requested changes
Please also see these comments. When you have finished your changes, press on `Re-request review` .

Also, rebase into a single commit. You can use the command `git rebase -i HEAD~<#commits_you_want_to_rebase> (example git rebase -i HEAD~8).  Afterwards, a force push will be needed.

2023-07-15 12:48 UTC, RaduNichita commented on app-ffmpeg-source/README.md
> +./lua
I think here should be `ffmpeg`

2023-07-15 12:48 UTC, RaduNichita commented on app-ffmpeg-source/README.md
> +With no arguments, it will display the following message.
```suggestion
When running the application with no arguments, it will display the following message:
```

2023-07-15 14:13 UTC, StefanJum requested changes
Looks really nice, see the few minor comments.

2023-07-15 14:13 UTC, StefanJum commented on app-ffmpeg-source/README.md
> +```
```suggestion
```text
```

2023-07-15 14:13 UTC, StefanJum commented on app-ffmpeg-source/README.md
> +```
```suggestion
```console
```

2023-07-15 14:13 UTC, StefanJum commented on app-ffmpeg-source/README.md
> +When trying to output files, you need to run the script `./run.sh` script with `sudo`.
```suggestion
## Important

When trying to output files, you need to run the script `./run.sh` script with `sudo`.
```

Leave an empty space before and after the headers

2023-07-15 14:13 UTC, StefanJum commented on app-ffmpeg-source/build.sh
> +popd &> /dev/null
```suggestion
popd &> /dev/null || exit 1
```

2023-07-17 12:38 UTC, StefanJum requested changes
Few more comments @razvang0307

2023-07-17 12:38 UTC, StefanJum commented on app-ffmpeg-source/build.sh
> +pushd iputils &> /dev/null || exit 1
```suggestion
pushd ffmpeg &> /dev/null || exit 1
```

2023-07-17 12:38 UTC, StefanJum commented on app-ffmpeg-source/build.sh
> +make
```suggestion
make -j $(nproc)
```

2023-07-17 12:38 UTC, StefanJum commented on app-ffmpeg-source/README.md
> +```
```suggestion
```console
```

2023-07-17 12:38 UTC, StefanJum commented on app-ffmpeg-source/README.md
> +Run the `./build.sh` script. This will download and build ffmpeg in the app-ffmpeg directory.
```suggestion
Run the `./build.sh` script. This will download and build ffmpeg in the `app-ffmpeg` directory.
```

2023-09-09 12:38 UTC, StefanJum approved these changes
All good, thank you.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-09 12:38 UTC, merged