Add GnuPG dynamic application built from source
unikraft/dynamic-apps pull request #57
Opened 2023-07-15 13:09 UTC by andreistan26

#47
Add GnuPG dynamic application built from source. Added the `build.sh` file for building the app.

2023-07-15 13:44 UTC, RaduNichita requested changes
You don't need to include the libraries or other binary file, only the `build.sh` script and a `README.md` file in which you explain how to run the application on both Linux and Unikraft.

You can see an example [here](https://github.com/unikraft/dynamic-apps/pull/53)

2023-07-16 06:52 UTC, StefanJum requested changes
Thanks @andreistan26, see the comments.
Besides those, it seems like there is a lot of similar code for building different libraries, see if it makes sense to have a bash function that does that (receives an url and a name as parameters and does the job).

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/README.md
> +```
```suggestion
```console
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/README.md
> +In order to build `GnuPG` you have to run, from the **gnupg_source** directory
```suggestion
In order to build `GnuPG` you have to run, from the **gnupg_source** directory

```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/README.md
> +the `extract.sh` tool to generate the `lib` `lib64` and `bin` directories.
```suggestion
The script will download GnuPG and it's dependecies, build them and use the `extract.sh` tool to generate the `lib` `lib64` and `bin` directories.
```
Use one line per sentence and one sentence per line.

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
Run the script through [shellcheck](https://www.shellcheck.net/).

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +    echo "You need extract.sh in order to build!"
```suggestion
    echo "You need extract.sh in order to build!" 1>&2
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +wget -q https://gnupg.org/ftp/gcrypt/gpgrt/$LIBGPG_ERROR.tar.bz2
```suggestion
wget -q "https://gnupg.org/ftp/gcrypt/gpgrt/$LIBGPG_ERROR.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +tar xvf $LIBGPG_ERROR.tar.bz2 && rm -f $LIBGPG_ERROR.tar.bz2
```suggestion
tar xvf "$LIBGPG_ERROR.tar.bz2" && rm -f "$LIBGPG_ERROR.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd $LIBGPG_ERROR
```suggestion
pushd "$LIBGPG_ERROR" &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +    exit
```suggestion
    exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +    echo "Building $LIBGPG_ERROR failed!"
```suggestion
    echo "Building $LIBGPG_ERROR failed!" 1>&2
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd ..
```suggestion
popd &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +wget -q https://gnupg.org/ftp/gcrypt/libgcrypt/$LIBGC_CRYPT.tar.bz2
```suggestion
wget -q "https://gnupg.org/ftp/gcrypt/libgcrypt/$LIBGC_CRYPT.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +tar xvf $LIBGC_CRYPT.tar.bz2 && rm -f $LIBGC_CRYPT.tar.bz2
```suggestion
tar xvf "$LIBGC_CRYPT.tar.bz2" && rm -f "$LIBGC_CRYPT.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd $LIBGC_CRYPT
```suggestion
pushd "$LIBGC_CRYPT" &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd ..
```suggestion
popd &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd $LIBASSUAN
```suggestion
pushd "$LIBASSUAN" &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd ..
```suggestion
popd &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +wget -q https://gnupg.org/ftp/gcrypt/libassuan/$LIBASSUAN.tar.bz2
```suggestion
wget -q "https://gnupg.org/ftp/gcrypt/libassuan/$LIBASSUAN.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +tar xvf $LIBASSUAN.tar.bz2 && rm -f $LIBASSUAN.tar.bz2
```suggestion
tar xvf "$LIBASSUAN.tar.bz2" && rm -f "$LIBASSUAN.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +wget -q https://gnupg.org/ftp/gcrypt/libksba/libksba-1.6.4.tar.bz2
```suggestion
wget -q "https://gnupg.org/ftp/gcrypt/libksba/libksba-1.6.4.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +tar xvf $LIBKSBA.tar.bz2 && rm -f $LIBKSBA.tar.bz2
```suggestion
tar xvf "$LIBKSBA.tar.bz2" && rm -f "$LIBKSBA.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd $LIBKSBA
```suggestion
pushd "$LIBKSBA" &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +
```suggestion

```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd ..
```suggestion
popd &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +wget -q https://gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2
```suggestion
wget -q "https://gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +tar xvf $LIBNPTH.tar.bz2 && rm -f $LIBNPTH.tar.bz2
```suggestion
tar xvf "$LIBNPTH.tar.bz2" && rm -f "$LIBNPTH.tar.bz2"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd $LIBNPTH
```suggestion
pushd "$LIBNPTH" &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd ..
```suggestion
popd &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd $LIBGNUPG
```suggestion
pushd "$LIBGNUPG" &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +cd ..
```suggestion
popd &> /dev/null || exit 1
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +rm -rf $LIBGC_CRYPT
```suggestion
rm -rf "$LIBNPTH"
rm -rf "$LIBKSBA"
rm -rf "$LIBASSUAN"
rm -rf "$LIBGPG_ERROR"
rm -rf "$LIBGC_CRYPT"
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +    cp $LIBGNUPG/$binary bin
```suggestion
    cp "$LIBGNUPG/$binary" bin
```

2023-07-16 06:52 UTC, StefanJum commented on gnupg_source/build.sh
> +    ./extract.sh $LIBGNUPG/$binary
```suggestion
    ./extract.sh "$LIBGNUPG/$binary"
```

2023-07-16 09:29 UTC, andreistan26 commented
Thanks for all the tips. I've [refactored](https://github.com/unikraft/dynamic-apps/pull/57/commits/0371ae8f398a2a1f8b595b314d01e08147b3c04d?short_path=9e04612#diff-9e04612a2229595cfc780aa59b9fd5662e5540a82d99322752cc66d3a9cea1bc) both the `README` and the `build.sh`. They are ready for another review.

2023-07-16 11:52 UTC, StefanJum requested changes
Looks a lot better @andreistan26, few more comments, hopefully the last ones.

2023-07-16 11:52 UTC, StefanJum commented on gnupg_source/README.md
> +executable in any Linux ELF-compatible environment: native Linux, chroot/jail, Docker, Unikraft.
```suggestion
This directory stores the `build.sh` file, used for building [GnuPG]("https://gnupg.org/"), also known as `gpg`, a command line tool for encrypting and singing your data.
All files are stored in their expected location in the Linux filesytem hierarchy.
The aim is to run the executable in any Linux ELF-compatible environment: native Linux, chroot/jail, Docker, Unikraft.
```
Use one line per sentence and one sentence per line

2023-07-16 11:52 UTC, StefanJum commented on gnupg_source/README.md
> +For more about the usage of `gpg` visit the [official documentation](https://www.gnupg.org/documentation/)
```suggestion
For more about the usage of `gpg` visit the [official documentation](https://www.gnupg.org/documentation/).
```

2023-07-16 11:52 UTC, StefanJum commented on gnupg_source/README.md
> +directory
```suggestion
In order to build `GnuPG` you have to run, from inside the **gnupg_source**  directory.
```
Use one line per sentence and one sentence per line

2023-07-16 11:52 UTC, StefanJum commented on gnupg_source/README.md
> +the `extract.sh` tool to generate the `lib` `lib64` and `bin` directories.
```suggestion
The script will download GnuPG and it's dependecies, build them and use the `extract.sh` tool to generate the `lib` `lib64` and `bin` directories.
```

2023-07-16 11:52 UTC, StefanJum commented on gnupg_source/README.md
> +[`run-app-elfloader` repository](https://github.com/unikraft/run-app-elfloader):
```suggestion
To run the binary ELF on Unikraft, run the `run.sh` script from the  [`run-app-elfloader` repository](https://github.com/unikraft/run-app-elfloader):
```

2023-07-16 11:52 UTC, StefanJum commented on gnupg_source/build.sh
> +get_and_build $LIBGNUPG $LIBGNUPG_URL
```suggestion
get_and_build "$LIBGPG_ERROR" "$LIBGPG_ERROR_URL"
get_and_build "$LIBGC_CRYPT" "$LIBGC_CRYPT_URL"
get_and_build "$LIBASSUAN" "$LIBASSUAN_URL"
get_and_build "$LIBKSBA" "$LIBKSBA_URL"
get_and_build "$LIBNPTH" "$LIBNPTH_URL"
get_and_build "$LIBGNUPG" "$LIBGNUPG_URL"
```

2023-07-16 12:33 UTC, andreistan26 commented
Should be fine now.

2023-07-16 12:44 UTC, StefanJum requested changes
@andreistan26 I get this error when running `./build.sh`

```
gcc -DWITHOUT_NPTH=1  -std=gnu99 -I/usr/local/include  -I/usr/include/p11-kit-1 -I/usr/local/include -I/usr/local/include -I/usr/local/include -Wall -Wno-format-zero-length -Wno-pointer-sign -Wpointer-arith -g -O2   -o t-http-basic t_http_basic-t-support.o t_http_basic-dns.o t_http_basic-t-http-basic.o t_http_basic-http.o t_http_basic-dns-stuff.o t_http_basic-http-common.o ../common/libcommon.a -L/usr/local/lib -lassuan  -L/usr/local/lib -lgcrypt -L/usr/local/lib -lgpg-error -lgnutls  -lresolv     -L/usr/local/lib -lksba -lgpg-error -L/usr/local/lib -lgcrypt -L/usr/local/lib -lgpg-error -lgnutls -lresolv  
/usr/bin/ld: server.o: in function `cmd_ad_query':
/home/stefan/projects/unikraft/usoc23/session-04/dynamic-apps/gnupg_source/gnupg-2.4.3/dirmngr/server.c:2779: undefined reference to `ks_ldap_help_variables'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:937: dirmngr] Error 1
```

2023-07-16 22:31 UTC, andreistan26 commented
That is weird, the undefined reference is not even an external dependency. We could try to add  `autoreconf -i` before running `./configure` for the files, maybe that can help. Also I've found the build process (gpg's) to be a little non deterministic, did you try to rerun the build process?

2023-07-17 12:46 UTC, StefanJum reviewed
See the one comment.
I still get the undefined reference error. Are you sure you did not install anything `ldap`-related besides running the script?
@RaduNichita @eduardvintila maybe you can try this too and see if it works for you.

2023-07-17 12:46 UTC, StefanJum commented on gnupg_source/build.sh
> +
There are some trailing whitespaces here

2023-07-17 16:22 UTC, andreistan26 commented on gnupg_source/build.sh
> +
Fixing those

2023-07-30 14:29 UTC, RaduNichita requested changes
It's looking better now, @andreistan26, thanks for the effort. I have left another round of feedback.

Please also rename the folder to be `gnupg_src`.

2023-07-30 14:29 UTC, RaduNichita commented on gnupg_source/README.md
> +The script will download GnuPG and it's dependecies, build them and use the `extract.sh` tool to generate the `lib` `lib64` and `bin` directories.
```suggestion
The script will download GnuPG and it's dependencies, build them and use the `extract.sh` tool to generate the `lib` `lib64` and `bin` directories.
```

2023-07-30 14:29 UTC, RaduNichita commented on gnupg_source/build.sh
> +echo "Donwloading dependencies ..."
```suggestion
echo "Downloading dependencies ..."
```

2023-07-30 14:29 UTC, RaduNichita commented on gnupg_source/build.sh
> +    echo ""
```suggestion

```

2023-07-30 14:29 UTC, RaduNichita commented on gnupg_source/build.sh
> +LIBGNUPG="gnupg-2.4.3"
I suggest that you put those at the beginning of the file.

2023-07-30 14:29 UTC, RaduNichita commented on gnupg_source/build.sh
> +mv usr/local/lib/libgpg-error.so.0 lib/x86_64-linux-gnu
```suggestion
mv ./usr/local/lib/libgpg-error.so.0 ./lib/x86_64-linux-gnu
```

2023-07-30 14:29 UTC, RaduNichita commented on gnupg_source/README.md
> +## How to Build
```suggestion
## Build
```

2023-07-30 14:29 UTC, RaduNichita commented on gnupg_source/README.md
> +## How to Run on Unikraft
```suggestion
## Run
```

2023-07-30 14:29 UTC, RaduNichita commented on gnupg_source/README.md
> +The script will download GnuPG and it's dependecies, build them and use the `extract.sh` tool to generate the `lib` `lib64` and `bin` directories.
```suggestion
The script will download the GnuPG, install the required dependencies and build the sources.
```

2023-07-30 14:32 UTC, RaduNichita commented
Furthermore, modify the commit message so the signoff line would contain your real name, not your Github Id. 

Something line:

```console
Signed-off-by:  Andrei Stan <andreistan2003@gmail.com>
```

2023-08-02 17:19 UTC, andreistan26 commented
@RaduNichita have you tried running `build.sh` and if so, did you had any issues with it?

2023-09-09 11:52 UTC, StefanJum approved these changes
All good, thank you @andreistan26 
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-09 11:53 UTC, merged