Add nats-server application build from source
unikraft/dynamic-apps pull request #58
Opened 2023-07-15 14:42 UTC by SHOREQU69

Addresses issue: https://github.com/unikraft/dynamic-apps/issues/31

Co-authored-by: MekalBoy <23715925+MekalBoy@users.noreply.github.com>

2023-07-15 15:01 UTC, StefanJum requested changes
@SHOREQU69 you don't need to add the binaries, just the `build.sh` script.
Run the script through [shellcheck](https://www.shellcheck.net/).
Replace `cd x/y/z` with `pushd x/y/z &> /dev/null || exit 1` and `cd ..` with `popd &> /dev/null || exit 1`

2023-07-15 15:01 UTC, RaduNichita reviewed
Nice job, @SHOREQU69. 

Please change your email addreses in the commit message and see the other comments below.

2023-07-15 17:02 UTC, SHOREQU69 commented on nats-server/build.sh
> +echo "Finished"
What do you mean by changing the email addreses? Is it the users.noreply.github.com?

2023-07-15 20:55 UTC, RaduNichita commented on nats-server/build.sh
> +echo "Finished"
Yeah, it should be your real email address.

2023-09-09 10:18 UTC, StefanJum approved these changes
All good, thanks @SHOREQU69.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-09 10:21 UTC, merged