`lang/c`: Add simple HTTP program
unikraft/dynamic-apps pull request #64
Opened 2023-09-14 18:18 UTC by razvand

Add source code, Makefile, prebuilt ELF, pre-etracted dynamic libraries. Document steps to (re)build and run in `README.md`.

2023-09-14 20:08 UTC, StefanJum requested changes
Few comments.
Besides those I would move the `helloworld`, `client` and `server` files from `lang/c/` to `lang/c/helloworld/`, `lang/c/server-client` or something similar. Right now the `http_server` directory gets lost between the bunch of files under `lang/c/`.

2023-09-14 20:08 UTC, StefanJum commented on lang/c/http_server/README.md
> +sudo ./run.sh -n -r ../dynamic-apps/lang/c++/http_server /http_server
```suggestion
sudo ./run.sh -n -r ../dynamic-apps/lang/c/http_server /http_server
```

2023-09-14 20:08 UTC, StefanJum commented on lang/c/http_server/http_server.c
> + */
I think this is the outdated licence header right?

2023-09-14 20:08 UTC, StefanJum commented on lang/c/http_server/README.md
> +# Simple C HTP Server
```suggestion
# Simple C HTTP Server
```

2023-09-15 05:37 UTC, razvand commented
@StefanJum , see now.

2023-09-15 06:05 UTC, StefanJum approved these changes
All good now.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-15 06:05 UTC, merged