`lang/c++`: Add simple HTTP program
unikraft/dynamic-apps pull request #65
Opened 2023-09-14 18:19 UTC by razvand

Add source code, Makefile, prebuilt ELF, pre-etracted dynamic libraries. Document steps to (re)build and run in `README.md`.

2023-09-14 20:14 UTC, StefanJum requested changes
Works fine, see the few comments. Similar to #64, I would add the `helloworld.cpp` file and everything related to that into `lang/c++/helloworld/`

2023-09-14 20:14 UTC, StefanJum commented on lang/c++/http_server/README.md
> +# Simple C++ HTP Server
```suggestion
# Simple C++ HTTP Server
```

2023-09-14 20:14 UTC, StefanJum commented on lang/c++/http_server/http_server.cpp
> + */
This is the old licence header.

2023-09-15 05:42 UTC, razvand commented
@StefanJum , see now.

2023-09-15 06:09 UTC, StefanJum approved these changes
All good
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-15 06:10 UTC, merged