`lang/go`: Add simple HTTP program
unikraft/dynamic-apps pull request #66
Opened 2023-09-14 18:19 UTC by razvand

Add source code, Makefile, prebuilt ELF, pre-etracted dynamic libraries. Document steps to (re)build and run in `README.md`.

2023-09-14 20:20 UTC, StefanJum requested changes
Works fine, same as the other prs, I would move anything else under `lang/go/` in specific directories.

2023-09-14 20:20 UTC, StefanJum commented on lang/go/http_server/README.md
> +# Simple Go HTP Server
```suggestion
# Simple Go HTTP Server
```

2023-09-15 06:04 UTC, razvand commented
@StefanJum , see now.

2023-09-15 06:14 UTC, StefanJum approved these changes
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-15 06:14 UTC, merged