`lang`: Add Linux pre-built Python interpreter
unikraft/dynamic-apps pull request #68
Opened 2023-09-14 18:21 UTC by razvand

Add a Linux pre-built Python interpreter. Add pre-built ELF, pre-etracted dynamic libraries, Python libraries archive (in `usr.tar.gz`).  Document steps to run in `README.md`.

2023-09-14 20:31 UTC, StefanJum requested changes
I get some weird errors when trying to run the server on Unikraft (it works fine if I run it natively on linux):
```
>>>   File "//http_server.py", line 1
    try:
IndentationError: unexpected indent
>>>   File "//http_server.py", line 1
    webServer.serve_forever()
IndentationError: unexpected indent
>>>   File "//http_server.py", line 1
    except KeyboardInterrupt:
IndentationError: unexpected indent
>>>   File "//http_server.py", line 1
    pass
IndentationError: unexpected indent
>>> >>>   File "//http_server.py", line 1
    webServer.server_close()
IndentationError: unexpected indent
>>>   File "//http_server.py", line 1
    print("Server stopped.")
IndentationError: unexpected indent
```

Also, I think the `custom-build` directory should be named `python-custom-build` or should be places inside `lang/python/`.

2023-09-14 20:31 UTC, StefanJum commented on lang/python/README.md
> +```console
```suggestion
```console
./python http_server.py
```

2023-09-15 06:28 UTC, razvand commented
@StefanJum , I'm checking the issue now. It may be because of an outdated app-elfloader build.

2023-09-15 14:48 UTC, StefanJum approved these changes
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-15 14:48 UTC, StefanJum commented
Will leave the http server issue as it is, since it is not related to this pr.

2023-09-15 14:48 UTC, merged