Grep: Add grep dynamic executable
unikraft/dynamic-apps pull request #71
Opened 2023-09-19 10:21 UTC by chococandy63

Add the `grep` command of the grep command line utility.
Document usage of the `grep` command in `README.md`.

2023-09-23 11:53 UTC, StefanJum requested changes
Thanks a lot @chococandy63, looks great.
See the few comments, and please use your real name in the commit `signed-off-by` tag.

2023-09-23 11:53 UTC, StefanJum commented on grep/README.md
> +
```suggestion

```
Don't use multiple consecutive blanc lines.

2023-09-23 11:53 UTC, StefanJum commented on grep/README.md
> +
```suggestion
```

2023-09-23 11:53 UTC, StefanJum commented on grep/README.md
> +
```suggestion
```

2023-09-23 11:53 UTC, StefanJum commented on grep/README.md
> +
```suggestion
```

2023-09-23 11:53 UTC, StefanJum commented on grep/README.md
> +```
Give a snippet of what the output of the `run.sh` will be, both here and in the linux run section.

2023-09-24 09:29 UTC, chococandy63 commented
Hello @StefanJum 
I have made the necessary changes requested by you, kindly check!

2023-09-24 14:01 UTC, StefanJum requested changes
Few more comments @chococandy63, hopefully the last ones.

2023-09-24 14:01 UTC, StefanJum commented on grep/README.md
> +Output:
```suggestion

Output:

```

2023-09-24 14:01 UTC, StefanJum commented on grep/README.md
> +## Run the `grep` command on Linux
```suggestion

## Run the `grep` command on Linux

```

2023-09-24 14:01 UTC, StefanJum commented on grep/README.md
> +```console
```suggestion
To test the `grep` command run:

```console
```

2023-09-24 14:01 UTC, StefanJum commented on grep/README.md
> +For example, when in the current directory, run:
```suggestion

For example, when in the current directory, run:

```

2023-09-24 14:01 UTC, StefanJum commented on grep/README.md
> +Output:
```suggestion

Output:

```

2023-09-24 17:47 UTC, chococandy63 commented
@StefanJum  Thank you for the reviews, I have made the changes. Hopefully, everything is fine this time :)

2023-09-24 23:00 UTC, chococandy63 commented
@StefanJum  I pushed new changes(new commit) to the remote repository but I don't know how it got merged with this `grep` commit. Could you please guide me through this?

2023-09-24 23:14 UTC, StefanJum commented
@chococandy63 first make a copy, make sure you have everything saved in case we mess something up.
Then:

```
git rebase -i HEAD~3 # <-- this will open a text editor with the commits
                                      # remove the line with the `file` commit (the lasts one probably)
                                      # save and exit

git log # <-- the `file` commit should be gone
git push --force
```

2023-09-24 23:29 UTC, chococandy63 commented
@StefanJum  Thank you! Looks fine to me, Can you please review this PR?

2023-09-24 23:32 UTC, StefanJum reviewed
One more comment @chococandy63, all good after that.

2023-09-24 23:32 UTC, StefanJum commented on grep/README.md
> +```
```suggestion
```text
```

2023-09-24 23:56 UTC, chococandy63 commented on grep/README.md
> +```
@StefanJum  Done all the changes.

2023-09-25 00:19 UTC, StefanJum approved these changes
All good now, thanks a lot @chococandy63 
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-09-25 00:21 UTC, merged